
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzdWFyaW8zIiwiaWQiOiI2ODk3ZWZlODhiZmI4NjljMjcwZjE1YTAiLCJpYXQiOjE3NTU0NzIzMDN9.k3BucPJmWMuQpQ9jJV71RryDAudmtO5S7KfzfFUZuRQ

{
    "title": "va a ser borrado",
    "author": "Usuario 3",
    "url": "lo borraremos",
    "likes": 8
}